export const INDIAN_STATES = [
  "Andaman & Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const CREATOR_LANGUAGES = [
  "Assamese",
  "Bengali",
  "Bhojpuri",
  "Bodo",
  "Dogri",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Kashmiri",
  "Konkani",
  "Malayalam",
  "Maithili",
  "Manipuri",
  "Marathi",
  "Nepali",
  "Odia",
  "Punjabi",
  "Rajasthani",
  "Sanskrit",
  "Santali",
  "Sindhi",
  "Tamil",
  "Telugu",
  "Urdu",
];

export const CREATOR_NICHES = [
  "Agriculture & Rural Business",
  "Beauty & Skincare",
  "Comedy & Entertainment",
  "DIY & Crafts",
  "Education & Tutorials",
  "Fashion & Lifestyle",
  "Family & Parenting",
  "Food & Home Cooking",
  "Gaming",
  "Health & Wellness",
  "Music & Dance",
  "Motivation & Self-help",
  "Personal Finance",
  "Politics & News",
  "Spiritual & Devotional",
  "Sports & Fitness",
  "Street Food",
  "Tech & Gadgets",
  "Travel & Culture",
];

export const CREATOR_PLATFORMS = [
  "Instagram",
  "YouTube",
  "Facebook",
  "Moj",
  "ShareChat",
  "Josh",
  "Twitter/X",
  "LinkedIn",
  "Snapchat",
  "Koo",
];

export const BRAND_CATEGORIES = [
  "Agriculture & Rural Tech",
  "Beauty & Personal Care",
  "Consumer Electronics",
  "E-commerce & D2C",
  "Ed-Tech",
  "Fashion & Apparel",
  "Fintech & Banking",
  "Food & Beverages",
  "Health & Pharma",
  "Automobile",
  "Logistics & Supply Chain",
  "Media & Entertainment",
  "Real Estate",
  "Travel & Hospitality",
  "Other",
];

export const BRAND_BUDGETS = [
  "Under ₹1 lakh",
  "₹1–3 lakhs",
  "₹3–5 lakhs",
  "₹5–10 lakhs",
  "₹10–25 lakhs",
  "₹25 lakhs+",
];

export const BRAND_GOALS = [
  "Build regional awareness",
  "Launch a new product",
  "Drive store visits",
  "Generate qualified leads",
  "Create reusable content",
  "Grow social engagement",
];

export const PINCODE_LOCATIONS = {
  110001: { city: "New Delhi", state: "Delhi", district: "New Delhi" },
  400001: { city: "Mumbai", state: "Maharashtra", district: "Mumbai" },
  560001: { city: "Bengaluru", state: "Karnataka", district: "Bengaluru Urban" },
  700001: { city: "Kolkata", state: "West Bengal", district: "Kolkata" },
  751001: { city: "Bhubaneswar", state: "Odisha", district: "Khordha" },
  758001: { city: "Keonjhar", state: "Odisha", district: "Kendujhar" },
  800001: { city: "Patna", state: "Bihar", district: "Patna" },
};
